config/routes.rb
Pollockprints::Application.routes.draw do
  devise_for :views

  resources :prints

  devise_for :users
  
  root :to => 'prints#index'

end

app/models/print.rb
class Print < ActiveRecord::Base
  attr_accessible :image, :name, :paper, :press, :process, :year, :size, :ebeans, :paypal, :release_date, :run_size
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  # GET /prints
  # GET /prints.json
  def index
    @prints = Print.order("release_date DESC").page(params[:page]).per_page(6)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prints }
    end
  end

  # GET /prints/1
  # GET /prints/1.json
  def show
    @print = Print.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @print }
    end
  end

  # GET /prints/new
  # GET /prints/new.json
  def new
    @print = Print.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @print }
    end
  end

  # GET /prints/1/edit
  def edit
    @print = Print.find(params[:id])
  end

  # POST /prints
  # POST /prints.json
  def create
    @print = Print.new(params[:print])

    respond_to do |format|
      if @print.save
        format.html { redirect_to @print, notice: 'Print was successfully created.' }
        format.json { render json: @print, status: :created, location: @print }
      else
        format.html { render action: "new" }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prints/1
  # PUT /prints/1.json
  def update
    @print = Print.find(params[:id])

    respond_to do |format|
      if @print.update_attributes(params[:print])
        format.html { redirect_to @print, notice: 'Print was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prints/1
  # DELETE /prints/1.json
  def destroy
    @print = Print.find(params[:id])
    @print.destroy

    respond_to do |format|
      format.html { redirect_to prints_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/layouts/_footer.html.erb
	<div class="footer">
  		<small>
    		<%= link_to "Pollockprints.com", "http://pollockprints.com/wordpress" %>
  		</small>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
                         <a class="brand" href="/">Pollockprints</a>

             <ul class="nav pull-right">
                      <% if user_signed_in? %>
						<li><%= link_to "Add +", new_print_path %></li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
			</ul>
		</div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollockprints</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	
<div class="masonry js-masonry"
	  data-masonry-options='{ "columnWidth": 60, "isFitWidth": true }'>
            <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>
	<%= yield %>
		<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/prints/_form.html.erb
<%= simple_form_for(@print, html: { class: 'form-horizontal'}) do |f| %>
  <% if @print.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@print.errors.count, "error") %> prohibited this print from being saved:</h2>

      <ul>
      <% @print.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :image %>
    
    <%= f.input :name %>

	<%= f.input :size %>
    
    <%= f.input :process %>

    <%= f.input :paper %>

	<%= f.input :run_size %>

    <%= f.input :press, :collection => ['Bookbinding', 'Washington Iron Hand', 'Vandercook 320g', 'Heidelberg Cylinder Press'] %>

    <%= f.input :ebeans %>

	<%= f.input :paypal %>

	<%= f.input :release_date, { :start_year => 1995 } %>

  <div class="form-actions">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/prints/_print.html.erb
<div class="box">
    <%= link_to (image_tag print.image), print %>
    <p class="description">
        <%= print.name %>
    </p>
    <p>
        <strong>
            <%= print.year %>
        </strong>
    </p>
    <% if user_signed_in? %>
        <p>
          <%= link_to 'Edit', edit_print_path(print) %>
          <%= link_to 'Destroy', print, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/prints/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @print %> |
<%= link_to 'Back', prints_path %>

app/views/prints/index.html.erb
<div id="container"><%= will_paginate @prints %>
</div>
<div id="prints">
  <%= render @prints %>
</div>

app/views/prints/new.html.erb
<h1>New print</h1>

<%= render 'form' %>

<%= link_to 'Back', prints_path %>

app/views/prints/show.html.erb
<div class="container">
	<div class="row">
	
	<div class="span7"> <%= image_tag (@print.image) %> </div>

  	<div class="span5"> <p><h3><%= @print.name %></h3></p>
  	<p><h4><%= @print.year %></h4></p>

  	<p><%= @print.process %> print on <%= @print.paper %> paper. Run of <%= @print.run_size %>. Printed on <%= @print.press %> press</p>

	<% unless @print.ebeans.blank? %>
		<a href="http://expressobeans.com/public/detail.php/<%= @print.ebeans %>">Expressobeans Page</a>
	<% end %>

	<% if user_signed_in? %>
        <p>
			<%= link_to 'Edit', edit_print_path(@print) %> |
			<%= link_to 'Back', prints_path %>
		</p>
	<% end %>
</div>
</div>
</div>